name: Housing
main: me.Strobe.Housing.Main
version: 1.0
depend:
  - GTACore
  - Vault
commands:
  house:
    description: Base command

permissions:
  houses.commands:
    house:
      description: Allows for the usage of the base command
    houses.admin:
      description: Allows for the managament of Houses

